[package]
name = "fuzz_ack_message"
version = "3.1.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"
publish = false

[dependencies]
honggfuzz = "0.5"
log = "0.4.8"
# Local dependencies
mavryk_messages = { path = "../../mavryk/messages" }