[package]
name = "mavryk_messages"
version = "3.1.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
anyhow = "1.0"
bytes = "1"
time = { version = "0.3", features = ["formatting", "parsing"] }
derive_builder = "0.9"
thiserror = "1.0"
getset = "0.1"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_trace"] }
strum = "0.20"
strum_macros = "0.20"
num-bigint = "0.3"
num-traits = "0.2.8"
nom = "6.1"
# local dependencies
crypto = { path = "../../crypto" }
mavryk_encoding = { path = "../encoding" }
mavryk_encoding_derive = { path = "../encoding-derive" }
mavryk_identity = { path = "../identity" }
quickcheck = "1.0.3"
quickcheck_derive = { git = "https://github.com/tezedge/quickcheck_derive" }
rand = "0.7.3"

fuzzcheck = { git = "https://github.com/tezedge/fuzzcheck-rs.git", optional = true }

[[bench]]
name = "message_benchmark"
harness = false

[[bench]]
name = "decoders_benchmark"
harness = false

[[bench]]
name = "encoders_benchmark"
harness = false

[[bench]]
name = "operation_benchmark"
harness = false

[dev-dependencies]
assert-json-diff = "2"
criterion = { version = "0.3", features = ["html_reports"]}
csv = "1.1"
serde_json = "1.0"


[features]
fuzzing = ["fuzzcheck", "crypto/fuzzing", "mavryk_encoding/fuzzing", "mavryk_encoding_derive/fuzzing", "mavryk_identity/fuzzing"]

