[package]
name = "protocol-runner"
version = "3.1.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
clap = "2.33"
ctrlc = "3.1.3"
thiserror = "1.0"
tikv-jemallocator = "0.4.3"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.6"
slog-term = "2.9"
# local dependencies
crypto = { path = "../crypto" }
mavryk_api = { path = "../mavryk/api" }
mavryk_context = { path = "../mavryk/context" }
mavryk_context_api = { path = "../mavryk/context-api" }
mavryk_interop = { path = "../mavryk/interop" }
mavryk_messages = { path = "../mavryk/messages" }
ocaml-interop = { version = "0.8.7", features = ["without-ocamlopt", "caml-state"] }

