[package]
name = "mavryk_data_encoding"
version = "0.6.0"
authors = [
    "TriliTech <contact@trili.tech>",
    "Mavryk Dynamics <info@mavryk.io>"
]
edition = "2021"
rust-version = "1.64"
license = "MIT"
keywords = ["mavryk"]
categories = ["encoding"]
description = "Utilities for encoding/decoding data compatible with mavryk data encoding."
repository = "https://github.com/mavryk-network/mavryk-rust.git"

[dependencies]
bit-vec = "0.6.2"
thiserror = "1.0"
hex = "0.4"
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
num-traits = "0.2.8"
serde = { version = "1.0", features = ["derive"] }
nom.workspace = true
bitvec = "1.0"
lazy_static = "1.4"

[dependencies.mavryk_data_encoding_derive]
path = "../mavryk-encoding-derive"
version = "0.6.0"

[dev-dependencies]
serde_json = "1.0"

[features]
