[package]
name = "mavryk_context_ipc_client"
version = "3.1.1"
edition = "2021"
rust-version = "1.58"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
# local dependencies
async_ipc = { path = "../../async-ipc" }
crypto = { path = "../../crypto" }
mavryk_context_api = { path = "../context-api" }
mavryk_protocol_ipc_client = { path = "../protocol-ipc-client" }
