[package]
name = "mavryk_api"
version = "3.1.1"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
anyhow = "1.0"
derive_builder = "0.9"
thiserror = "1.0"
time = { version = "0.3", features = ["parsing"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_trace"] }
strum = "0.20"
strum_macros = "0.20"
nom = "6.1"
num-bigint = "0.3"
url = "2.2"
# local dependencies
crypto = { path = "../../crypto" }
mavryk_encoding = { path = "../encoding" }
mavryk_messages = { path = "../messages" }
mavryk_context_api = { path = "../context-api" }
fuzzcheck = { git = "https://github.com/tezedge/fuzzcheck-rs.git", optional = true }

[dev-dependencies]
assert-json-diff = "2"
hex = "0.4"

[features]
fuzzing = ["fuzzcheck", "crypto/fuzzing", "mavryk_encoding/fuzzing", "mavryk_messages/fuzzing", "mavryk_context_api/fuzzing"]

